# Generated by Django 5.0.1 on 2024-01-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('factor_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_name', models.CharField(max_length=50)),
                ('food_price', models.IntegerField()),
                ('food_code', models.IntegerField(primary_key=True, serialize=False)),
                ('food_off_code', models.CharField(default=0, max_length=3)),
                ('food_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_name', models.CharField(max_length=50)),
                ('section_code', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
